Signin UI
antonieto/ibm-dashboard pull request #161
Opened 2023-05-02 18:31 UTC by Jhoscar22

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Signin UI

* **What is the current behavior?** (You can also link to an open issue here)
No signin page

* **What is the new behavior (if this is a feature change)?**
Now there is a signin UI at the /signin route

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

2023-05-02 19:09 UTC, DavBot02 commented on data-dashboard/pages/signup.tsx
> +function SignIn() {
Signup

2023-05-02 19:10 UTC, Int-Angel requested changes
I think you should change all "signin" for "signup"

2023-05-02 19:10 UTC, Int-Angel commented on data-dashboard/pages/signup.tsx
> +function SignIn() {
I think this should be SignUp

2023-05-02 19:15 UTC, Jhoscar22 commented on data-dashboard/pages/signup.tsx
> +function SignIn() {
Done!

2023-05-02 19:19 UTC, Int-Angel approved these changes
LGTM!

2023-05-03 01:30 UTC, DavBot02 approved these changes

2023-05-03 02:50 UTC, merged