Feat - chart types
antonieto/ibm-dashboard pull request #169
Opened 2023-05-05 18:19 UTC by Int-Angel

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Added the 3 types of charts

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

2023-05-05 18:55 UTC, antonieto requested changes

2023-05-05 18:55 UTC, antonieto commented on data-dashboard/lib/components/Chart/Chart.tsx
> +export enum ChartType {
```suggestion
export type ChartType = 'bar' | 'line' | 'pie'
```

2023-05-05 18:55 UTC, antonieto commented on data-dashboard/lib/components/Chart/Chart.tsx
> +  chartProps: any;
This is very dangerous, please find a better way to define `chartProps`.

2023-05-05 18:55 UTC, antonieto commented on data-dashboard/lib/components/Chart/Chart.tsx
> +  chartProps: any;
This might work.
```suggestion
  chartProps: React.ComponentProps<typeof BarChart>;
```

2023-05-05 19:18 UTC, antonieto requested changes

2023-05-08 14:33 UTC, antonieto submitted a review, later dismissed

2023-05-09 01:43 UTC, paotg123 approved these changes

2023-05-09 01:44 UTC, paotg123 submitted a review, later dismissed
👍🏼

2023-05-16 01:05 UTC, antonieto requested changes

2023-05-16 01:05 UTC, antonieto commented on yarn.lock
Se coló este file prime

2023-05-16 01:20 UTC, DavBot02 approved these changes

2023-05-16 01:24 UTC, Int-Angel commented on yarn.lock
alv

2023-05-16 01:30 UTC, antonieto approved these changes

2023-05-16 01:30 UTC, merged